name: GATidwell
favicon: null
layout_spectrum: 0.8477272179443389
typography_spectrum: 0.44109616964124143
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fdfffe'
    - '#6795f7'
    - '#fccc9e'
    - '#ce9f1c'
  brandStrength: 1
  lightness: 0.3824714752845466
  saturation: 0.7749252545181662
  rhythmicContrast: 0.17598853935487568
purpose: []
